### ISSUE TITLE
真・グループ制御を利用した状況下でのシーンチェンジによるオブジェクトの非表示

### ISSUE THREAD

**Issue by Hearth111** [kumrnm/aviutl-authentic-grouping#7]
真・グループ制御を利用した状況下でシーンチェンジを使用した場合、シーンチェンジよりもレイヤーが下にありその上で、グループ制御の対象となっているオブジェクトがシーンチェンジが終わるまでテキストや図形に関わらず非表示になる現象を確認しました。こちらの環境での再現性は高かったものの、プラグインとの相性かもしれませんので検証をお願い致します。

**Comment by kumrnm** [comment]
ご報告ありがとうございます。
当該事象について調査を行っておりますが、現時点で当環境での再現はできておりません。お手数ですが、当該事象が発生した箇所のタイムラインのスクリーンショットを添付して頂けますでしょうか。（シーンチェンジより上のレイヤーも含めて撮影して頂けますと幸いです）

**Comment by kumrnm** [comment]
v1.1.0にて内部実装が大幅に変更されたため、旧バージョンの不具合への対応は終了いたします。アップデート後に同様の事象が確認されましたら改めてご連絡ください。
